require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'mynsapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'OpenSSL-Universal'

  pod 'RNXUpdate', :path => '../node_modules/react-native-xupdate-new'

  target 'mynsappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.78.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mynsapp-tvOS' do
  # Pods for mynsapp-tvOS

  target 'mynsapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
